"""empty message

Revision ID: a9efa2db7189
Revises: 1e2211cba771
Create Date: 2022-05-11 09:34:43.163079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9efa2db7189'
down_revision = '1e2211cba771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'car', 'driver', ['driver_id'], ['id'])
    op.drop_column('car', 'driver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('driver', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.drop_column('car', 'driver_id')
    # ### end Alembic commands ###
